Session5
dontcopy/ASPNetCoreMasters pull request #4
Opened 2021-09-26 20:45 UTC by dontcopy

For review

2021-09-27 16:55 UTC, jegtugado requested changes
Hi sir. Some changes are needed.

Can you also check the ErrorController and remove [HttpGet] from the error action. This particular line may prevent the exception handling for the different Http verbs i.e. post, put, delete

I approved the previous PR so all changes needed will be on this PR. Thanks!

2021-09-27 16:55 UTC, jegtugado commented on ASPNetCoreMastersTodoList.Api/ASPNetCoreMastersTodoList.Api/ApiModels/ItemApiModel.cs
> +        [Required]
a better practice in REST is to remove the required attribute and get the itemId from the route parameters

2021-09-27 17:18 UTC, dontcopy commented on ASPNetCoreMastersTodoList.Api/ASPNetCoreMastersTodoList.Api/ApiModels/ItemApiModel.cs
> +        [Required]
Is it redundant to have the itemId in the route parameter and in the model? Can we just have the id in the model or is there a benefit for the recommended approach?

2021-09-27 17:22 UTC, dontcopy commented on ASPNetCoreMastersTodoList.Api/ASPNetCoreMastersTodoList.Api/Data/ItemService.cs
> +            return _mapper.Map<IEnumerable<ItemDTO>>(_repository.All());
What kind of filter is expected? Will it be like size=3,id=3,text=anything, etc...

2021-09-27 17:26 UTC, jegtugado commented on ASPNetCoreMastersTodoList.Api/ASPNetCoreMastersTodoList.Api/Data/ItemService.cs
> +            return _mapper.Map<IEnumerable<ItemDTO>>(_repository.All());
yes. those are possible values that could be passed

2021-09-27 17:28 UTC, jegtugado commented on ASPNetCoreMastersTodoList.Api/ASPNetCoreMastersTodoList.Api/ApiModels/ItemApiModel.cs
> +        [Required]
if we are to follow rest architecture properly, we don't need the itemId from the model which means you can remove it. Imagine the client sending the id in both the url and body which is redundant

2021-10-01 15:25 UTC, jegtugado commented on ASPNetCoreMastersTodoList.Api/ASPNetCoreMastersTodoList.Api/Data/ItemService.cs
> +            return _mapper.Map<IEnumerable<ItemDTO>>(_repository.All());
Hi sir, on session 4 homework there is an example route for the filterBy. i.e. "/items/filterBy?text=text" you can use this as a test case for the filter

2021-10-01 15:27 UTC, jegtugado commented on ASPNetCoreMastersTodoList.Api/ASPNetCoreMastersTodoList.Api/ApiModels/ItemApiModel.cs
> +        [Required]
I also meant to say here that changing this is not required as my comment is a recommendation

2021-10-03 11:43 UTC, jegtugado approved these changes

2021-10-03 11:43 UTC, merged